import type { SpriteAssetManifest, SpriteAssetManifestEntry } from "@/lib/companion/sprite-manifest-types";

let cached: Map<number, SpriteAssetManifestEntry> | null = null;
let cachedAt = 0;
let loadAttempted = false;
const CACHE_MS = 5 * 60 * 1000;

export function markSpriteManifestLoadAttempted(): void {
  loadAttempted = true;
}

/** True after client manifest fetch finished (even when empty). */
export function isSpriteManifestLoadAttempted(): boolean {
  return loadAttempted;
}

function indexManifest(manifest: SpriteAssetManifest): Map<number, SpriteAssetManifestEntry> {
  return new Map(manifest.entries.map((e) => [e.nationalId, e]));
}

export function getSpriteManifestEntry(nationalId: number): SpriteAssetManifestEntry | null {
  return cached?.get(nationalId) ?? null;
}

export function setSpriteManifestCache(manifest: SpriteAssetManifest | null): void {
  if (!manifest?.entries?.length) {
    cached = null;
    cachedAt = 0;
    return;
  }
  cached = indexManifest(manifest);
  cachedAt = Date.now();
}

export function isSpriteManifestFresh(): boolean {
  return cached != null && Date.now() - cachedAt < CACHE_MS;
}

/** Fetch public manifest generated by `npm run sprites:upload`. */
export async function loadSpriteManifestFromPublic(): Promise<SpriteAssetManifest | null> {
  if (typeof window === "undefined") return null;
  try {
    const res = await fetch("/companion-sprite-manifest.json", { cache: "no-store" });
    if (!res.ok) return null;
    const body = (await res.json()) as SpriteAssetManifest;
    if (!body?.entries?.length) return null;
    setSpriteManifestCache(body);
    return body;
  } catch {
    return null;
  }
}
